In [3]:
import numpy as np
# we import the pytorch library
import torch
# we import the neural network module from pytorch
import torch.nn as nn


In [4]:
print('the vertion of pytorch is: ',torch.__version__)
print('the GPU is available: ',torch.cuda.is_available())

the vertion of pytorch is:  2.11.0+cu128
the GPU is available:  True


In [5]:
# we create a tensor of shape (3,2) with float32 data type 
x = torch.tensor([
                  [10, 20,50],
                  [30,40,50],
                  [50,60,70]],
                 dtype=torch.float32)

print('the shape of x is: ',x.shape)
print('the size of x Is: ',x.size())
print('the data type :',x.dtype)

the shape of x is:  torch.Size([3, 3])
the size of x Is:  torch.Size([3, 3])
the data type : torch.float32


In [6]:
# we have same data type of tensor like torch.float32, torch.float64, torch.int32, torch.int64
scaler = torch.tensor(9, dtype=torch.int64)
vector = torch.tensor([1,2,3],dtype=torch.float64)
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]] ,dtype=torch.float32)
#  the data type 
print('\nthe data type of scaler is: ',scaler.dtype)
print('the data type of vector is: ',vector.dtype)
print('the data type of matrix is: ',matrix.dtype)
# the shape 
print('\nthe shape of scaler is: ',scaler.shape)

print('the shape of vector is: ',vector.shape)
print('the shape of matrix is: ',matrix.shape)

# the number of dimensions of the tensor is called ndim
print('\nthe number of dimensions of scaler is: ',scaler.ndim)
print('the number of dimensions of vector is: ',vector.ndim)
print('the number of dimensions of matrix is: ',matrix.ndim)


the data type of scaler is:  torch.int64
the data type of vector is:  torch.float64
the data type of matrix is:  torch.float32

the shape of scaler is:  torch.Size([])
the shape of vector is:  torch.Size([3])
the shape of matrix is:  torch.Size([3, 3])

the number of dimensions of scaler is:  0
the number of dimensions of vector is:  1
the number of dimensions of matrix is:  2


In [7]:
# (Batch, Channels, Height, Width)  , torch.zeros() create a tensor filled with zeros, 
# torch.ones() create a tensor filled with ones,
# torch.rand() create a tensor filled with random numbers between 0 and 1
# torch.randn() create a tensor filled with random numbers from a normal distribution
eye = torch.eye(4 , dtype=torch.float32)
one = torch.ones((3,2),dtype=torch.float32)
rand = torch.rand((3,2),dtype=torch.float32)
randn = torch.randn((3,2),dtype=torch.float32)
image = torch.zeros((28,28),dtype=torch.float32)
arang = torch.arange(0,10,2,dtype=torch.float32 )
line = torch.linspace(1,4,20, dtype=torch.float32)


print('The eye :',eye)
print('The One ',one)
print('The Rand ',rand)
print('The Line ',line)
print('The Randn ',randn)
print('The Image Shape ',image.shape)
print('The Arang ',arang)

The eye : tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
The One  tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
The Rand  tensor([[0.6830, 0.8109],
        [0.0413, 0.5191],
        [0.7358, 0.1330]])
The Line  tensor([1.0000, 1.1579, 1.3158, 1.4737, 1.6316, 1.7895, 1.9474, 2.1053, 2.2632,
        2.4211, 2.5789, 2.7368, 2.8947, 3.0526, 3.2105, 3.3684, 3.5263, 3.6842,
        3.8421, 4.0000])
The Randn  tensor([[ 0.5364, -1.1867],
        [-0.3398, -0.4625],
        [ 0.4324, -0.9821]])
The Image Shape  torch.Size([28, 28])
The Arang  tensor([0., 2., 4., 6., 8.])


In [8]:
x = torch.tensor([
                  [10, 20,30],
                  [40,50,60],
                  [70,80,90]],
                 dtype=torch.float32)
#         Column
#        0   1   2
# Row 0 10  20  30
# Row 1 40  50  60
# Row 2 70  80  90
print(x[1,2]) # this way is fast 
print(x[1][2])
# the secane row 
print(x[1])
print(x[1,:])
# for the colume
print('the secan column: ',x[:,2])

# the part for the tensor , the slice work like this -> (Start : End)
# the slice save the same dimesion
print(x[:2,1:])





print(x)

tensor(60.)
tensor(60.)
tensor([40., 50., 60.])
tensor([40., 50., 60.])
the secan column:  tensor([30., 60., 90.])
tensor([[20., 30.],
        [50., 60.]])
tensor([[10., 20., 30.],
        [40., 50., 60.],
        [70., 80., 90.]])


In [9]:
# Ex 
x = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(x[1,2])
print(x[2,:])
print(x[:,0])
print(x[1:3,1:3])
print(x[:,3])

tensor(7)
tensor([ 9, 10, 11, 12])
tensor([1, 5, 9])
tensor([[ 6,  7],
        [10, 11]])
tensor([ 4,  8, 12])


In [10]:
y = torch.arange(1,13,dtype=torch.float32)
print(y)
print('the shape for (3,4): ',y.reshape(3,4))
print('\nthe shape for (4,3): ',y.reshape(4,3))
print('\nthe shape for (1,12): ',y.reshape(1,12))
print('\nthe shape for (12,1): ',y.reshape(12,1))
print('\nthe shape for (2,6): ',y.reshape(2,6))
print('\nthe shape for (6,2): ',y.reshape(6,2))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
the shape for (3,4):  tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

the shape for (4,3):  tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

the shape for (1,12):  tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

the shape for (12,1):  tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])

the shape for (2,6):  tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

the shape for (6,2):  tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [11]:
x = torch.arange(1,13,dtype = torch.float32)
print(x.reshape(3,-1)) # -1 it mean the number of item / and shape we will have like 3 in this examplo
print(x.reshape(-1,3)) # -1 == 4


# we have function x.view(3,2)  like the reshpe but it is not make a new tensor like reshape and it fast
print(x.view(3,4))

# but same time it fail like he
x = torch.arange(12).reshape(3,4)
y = x.T
print(y)
## print(y.view(3,4))  # error
# it is give this error (view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead)

# flatten()  it change  the matrex to vector like (3,4)  to -> vector of 12 item 
# Image

# ⬜⬛⬜⬛
# ⬛⬜⬛⬜
# ⬜⬛⬜⬛
# ⬛⬜⬛⬜

# to ⬜⬛⬜⬛⬛⬜⬛⬜⬜⬛⬜⬛⬛⬜⬛⬜
print(y.flatten())

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
tensor([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])


## Element-wise Operations

In [12]:
A = torch.arange(12).reshape(4,3) # -> matrx
B = torch.arange(12).reshape(3,4) # -> matrx
x = torch.tensor([1,2,3])         # -> vector
y = torch.tensor([4,5,6])

print('sum: ', x + y)
print('sub: ', x - y)
print('mult: ', x * y)
print('div: ', x / y)


# [0,1,2] * [4,5,6] = 17 ,  [3,4,5] * [4,5,6] = 62 , [6,7,8] * [4,5,6] = 107 , [9,10,11] * [4,5,6] = 152
print(torch.matmul(A, y))  # Broadcasting
print(torch.matmul(A, B)) 

sum:  tensor([5, 7, 9])
sub:  tensor([-3, -3, -3])
mult:  tensor([ 4, 10, 18])
div:  tensor([0.2500, 0.4000, 0.5000])
tensor([ 17,  62, 107, 152])
tensor([[ 20,  23,  26,  29],
        [ 56,  68,  80,  92],
        [ 92, 113, 134, 155],
        [128, 158, 188, 218]])


In [13]:
weight = torch.tensor([1,11,12])
bias = torch.tensor([1,2,3])
output = torch.matmul(x, weight) + bias # the linear model  
print(output)


tensor([60, 61, 62])


## Autograd

In [14]:
x = torch.tensor(2.0,requires_grad=True)
y = x ** 2
print(y.backward())
print(x.grad)

None
tensor(4.)


In [15]:
x = torch.tensor(2.0,requires_grad=True)
# Complex Function

y = (x**3 + 2*x**2 - 5*x + 7) * (4*x - 1)
# the dertv = (3*x**2+4*x−5) (4x−1)  +  (x*3+2*x**2−5*x+7) (4)
# Compute Gradient
y.backward()

print("y =", y.item())
print("dy/dx =", x.grad.item())

y = 91.0
dy/dx = 157.0


In [16]:


x = torch.arange(24).reshape(2,3,4)
print(x[1,2])

tensor([20, 21, 22, 23])


In [17]:
x = torch.tensor(3.0, requires_grad=True)

y = x**2

y.backward()

print(x.grad)

tensor(6.)


In [18]:
import torch.nn as nn
layer = nn.Linear(4,2) # 4 is input features and 2 is output features
# in side the Linear function -> w @ x + b      weight shape = (2,4) and bias shape = (2,)

In [19]:
layer1 = nn.Linear(4,2)
x = torch.randn(3,4) # 3 samples or the batch size and 4 features
y = layer1(x)
print(x.shape)
print(y.shape)

# 3 Samples
# Each Sample
#    ↓
# 4 Features
#    ↓
# Linear Layer
#    ↓
# 2 Features

print(layer1.weight.shape) # (2,4)
print(layer1.bias.shape) # (2,4)

torch.Size([3, 4])
torch.Size([3, 2])
torch.Size([2, 4])
torch.Size([2])


In [20]:
lay = nn.Linear(10,5)
x= torch.randn(8,10)
y = lay(x)
print(x.shape) # (5,10)
print(y.shape) # (5,)

torch.Size([8, 10])
torch.Size([8, 5])


In [21]:
# Example of a simple feedforward neural network with two linear layers
layers1 = nn.Linear(6,12)
layers2 = nn.Linear(12,4)
x = torch.randn(12,6)
y1 = layers1(x)
y2 = layers2(y1)
print('the shape of x is:', x.shape) # (12,6)
print('the shape of y1 is:', y1.shape) # (12,12)
print('the shape of y2 is:', y2.shape) # (12,4)


the shape of x is: torch.Size([12, 6])
the shape of y1 is: torch.Size([12, 12])
the shape of y2 is: torch.Size([12, 4])


In [22]:
import torch
import torch.nn as nn

relu = nn.ReLU()

x = torch.tensor([
    [-2.0, -1.0, 0.0, 1.0, 2.0]
])

print("Before ReLU:")
print(x)

y = relu(x)

print("\nAfter ReLU:")
print(y)

Before ReLU:
tensor([[-2., -1.,  0.,  1.,  2.]])

After ReLU:
tensor([[0., 0., 0., 1., 2.]])


## ReLU function 
Input
(32,4)

↓

fc1
(32,8)

↓

ReLU
(32,8)

↓

fc2
(32,2)

↓

Output

## Training Loop

In [23]:
import torch
import torch.nn as nn

# ==========================
# Model
# ==========================

class SimpleNN(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(4, 8)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(8, 2)

    def forward(self, x):

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)

        return x


model = SimpleNN()

# ==========================
# Data
# ==========================

x = torch.randn(100,4)
y = torch.randint(0,2,(100,))

# ==========================
# Loss
# ==========================

criterion = nn.CrossEntropyLoss()

# ==========================
# Optimizer
# ==========================

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

# ==========================
# Training Loop
# ==========================

epochs = 100

for epoch in range(epochs):

    outputs = model(x)

    loss = criterion(outputs, y)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    print(
        f"Epoch {epoch+1} | Loss = {loss.item():.4f}"
    )


Epoch 1 | Loss = 0.7164
Epoch 2 | Loss = 0.7155
Epoch 3 | Loss = 0.7146
Epoch 4 | Loss = 0.7138
Epoch 5 | Loss = 0.7130
Epoch 6 | Loss = 0.7122
Epoch 7 | Loss = 0.7114
Epoch 8 | Loss = 0.7107
Epoch 9 | Loss = 0.7099
Epoch 10 | Loss = 0.7092
Epoch 11 | Loss = 0.7085
Epoch 12 | Loss = 0.7078
Epoch 13 | Loss = 0.7071
Epoch 14 | Loss = 0.7064
Epoch 15 | Loss = 0.7057
Epoch 16 | Loss = 0.7051
Epoch 17 | Loss = 0.7044
Epoch 18 | Loss = 0.7038
Epoch 19 | Loss = 0.7032
Epoch 20 | Loss = 0.7026
Epoch 21 | Loss = 0.7020
Epoch 22 | Loss = 0.7014
Epoch 23 | Loss = 0.7008
Epoch 24 | Loss = 0.7002
Epoch 25 | Loss = 0.6996
Epoch 26 | Loss = 0.6991
Epoch 27 | Loss = 0.6986
Epoch 28 | Loss = 0.6980
Epoch 29 | Loss = 0.6975
Epoch 30 | Loss = 0.6970
Epoch 31 | Loss = 0.6964
Epoch 32 | Loss = 0.6959
Epoch 33 | Loss = 0.6954
Epoch 34 | Loss = 0.6949
Epoch 35 | Loss = 0.6944
Epoch 36 | Loss = 0.6940
Epoch 37 | Loss = 0.6935
Epoch 38 | Loss = 0.6930
Epoch 39 | Loss = 0.6925
Epoch 40 | Loss = 0.6921
Epoch 41 

In [24]:

x = torch.randn(100, 4)
y = torch.randint(0, 2, (100,))

# Rule: When using CrossEntropyLoss, don’t put Sigmoid or Softmax in the last layer
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(4, 8)
        self.fc2 = nn.Linear(8, 8)
        self.fc3 = nn.Linear(8, 2)
        self.relu = nn.ReLU()
    def forward(self, x):
        x =self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)    
        x = self.fc3(x)
        return x
model =SimpleNN()

output = model(x)

cross = nn.CrossEntropyLoss()


loss =  cross(output, y)

optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

for i in range(100):
    output = model.forward(x)
    loss = cross(output, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print(f"Epoch {i+1} - Loss: {loss.item():.4f}")

Epoch 1 - Loss: 0.6996
Epoch 2 - Loss: 0.6994
Epoch 3 - Loss: 0.6992
Epoch 4 - Loss: 0.6990
Epoch 5 - Loss: 0.6988
Epoch 6 - Loss: 0.6986
Epoch 7 - Loss: 0.6984
Epoch 8 - Loss: 0.6982
Epoch 9 - Loss: 0.6980
Epoch 10 - Loss: 0.6978
Epoch 11 - Loss: 0.6976
Epoch 12 - Loss: 0.6974
Epoch 13 - Loss: 0.6972
Epoch 14 - Loss: 0.6970
Epoch 15 - Loss: 0.6969
Epoch 16 - Loss: 0.6967
Epoch 17 - Loss: 0.6965
Epoch 18 - Loss: 0.6964
Epoch 19 - Loss: 0.6962
Epoch 20 - Loss: 0.6960
Epoch 21 - Loss: 0.6959
Epoch 22 - Loss: 0.6957
Epoch 23 - Loss: 0.6956
Epoch 24 - Loss: 0.6954
Epoch 25 - Loss: 0.6953
Epoch 26 - Loss: 0.6951
Epoch 27 - Loss: 0.6950
Epoch 28 - Loss: 0.6948
Epoch 29 - Loss: 0.6947
Epoch 30 - Loss: 0.6945
Epoch 31 - Loss: 0.6944
Epoch 32 - Loss: 0.6943
Epoch 33 - Loss: 0.6941
Epoch 34 - Loss: 0.6940
Epoch 35 - Loss: 0.6939
Epoch 36 - Loss: 0.6938
Epoch 37 - Loss: 0.6936
Epoch 38 - Loss: 0.6935
Epoch 39 - Loss: 0.6934
Epoch 40 - Loss: 0.6933
Epoch 41 - Loss: 0.6931
Epoch 42 - Loss: 0.6930
E

## Data Set

In [25]:
# __len__()  it return the number of samples in the dataset
# __getitem__()  it return a sample from the dataset given an index
# Dataset is an abstract class representing a dataset 
from torch.utils.data import Dataset ,DataLoader
x_batch = torch.randn(102, 4)
y_batch = torch.randn(102, 1)

class MyDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        return self.x[index], self.y[index]
print('the shape of x is: ',x_batch.shape)
print('the shape of y is: ',y_batch.shape)

data = MyDataset(x_batch, y_batch)

train_loader = DataLoader(data, batch_size=10, shuffle=True)
print('the length of train_loader is: ',len(train_loader))
for x_batch,y_batch in train_loader:
    print(f"x_batch shape = {x_batch.shape}, y_batch shape = {y_batch.shape}")
    


the shape of x is:  torch.Size([102, 4])
the shape of y is:  torch.Size([102, 1])
the length of train_loader is:  11
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([10, 4]), y_batch shape = torch.Size([10, 1])
x_batch shape = torch.Size([2, 4]), y_batch shape = torch.Size([2, 1])


In [26]:

from torchvision import datasets
from torchvision.transforms import ToTensor


train_data = datasets.MNIST(
    root='data',train=True , download=True, transform= ToTensor()
)
test_data = datasets.MNIST(
    root= 'data', train=False ,download=True, transform=ToTensor())

print('the length of train_data is: ',len(train_data))
print('the length of test_data is: ',len(test_data))

100%|██████████| 9.91M/9.91M [00:00<00:00, 12.8MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 337kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 3.16MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 14.5MB/s]

the length of train_data is:  60000
the length of test_data is:  10000


(N, C, H, W)

N = Batch Size, 
C = Channels, 
H = Height, 
W = Width

In [27]:
imges , label = train_data[0]
# (Channel, Height, Width) -.  the shape of imges is: torch.Size([1, 28, 28]) and the label of imges is:  5
#  the channel is 1 because the imges is black and white and the hight and width is 28 X 28
print('the shape of imges is: ',imges.shape)
print('the label of imges is: ',label)


train_loader = DataLoader(train_data, batch_size=64, shuffle=True)

for x_batch, y_batch in train_loader:
    print(f'end=> x_batch shape = {x_batch.shape}, y_batch shape = {y_batch.shape}')
    

imges , label = next(iter(train_loader))
print('the shape of imges is: ',imges.shape)
print('the shape of label is: ',label.shape)

# the Linear function is need (batch_size, features) but now we have (batch_size, channel, height, width) 
# so we need to flatten the imges to (batch_size, features) and the features = channel * height * width = 1 * 28 * 28 = 784

the shape of imges is:  torch.Size([1, 28, 28])
the label of imges is:  5
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
end=> x_batch shape = torch.Size([64, 1, 28, 28]), y_batch shape = torch.Size([64])
en

In [33]:
import torch 
import torch.nn as nn
class MNISTModel(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 10)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x
# print('the shape of imges is: ',MNISTModel().forward(torch.randn(64, 1, 28, 28)).shape)

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)

images, label = next(iter(train_loader))
images_test, label_test = next(iter(test_loader))


model = MNISTModel()

device = torch.device('cuda') if torch.cuda.is_available() else 'cpu'
model.to(device)

loss_fn = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

epochs = 10
for epoch in range(epochs):
    model.train()
    
    epoch_loss  = 0
    total = 0
    correct = 0
    
    for x_batch, y_batch in train_loader:
        x_batch, y_batch = x_batch.to(device), y_batch.to(device)
    
        output = model(x_batch)
        
        prediction = torch.argmax(output, dim=1)
     
        loss = loss_fn(output, y_batch)
    
        optimizer.zero_grad()
    
        loss.backward()
    
        optimizer.step()
        
        epoch_loss += loss.item()

        total += y_batch.size(0)
        correct += (prediction == y_batch).sum().item()
        
    print(f"Epoch {epoch+1} - Loss: {epoch_loss / len(train_loader):.4f}, Accuracy: {correct / total:.4f}")
    
        
    model.eval()

    correct = 0
    total = 0
    test_loss = 0

    with torch.no_grad():

        for x_batch, y_batch in test_loader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)

            output = model(x_batch)

            loss = loss_fn(output, y_batch)

            test_loss += loss.item()

            predictions = output.argmax(dim=1)

            correct += (predictions == y_batch).sum().item()

            total += y_batch.size(0)

    test_loss /= len(test_loader)

    accuracy = correct / total

    print(f"Test Loss: {test_loss:.4f}")
    print(f"Test Accuracy: {accuracy*100:.2f}%")
torch.save(model.state_dict(), "mnist_model.pth")
            


Epoch 1 - Loss: 0.3472, Accuracy: 0.9008
Test Loss: 0.1892
Test Accuracy: 94.21%
Epoch 2 - Loss: 0.1468, Accuracy: 0.9557
Test Loss: 0.1215
Test Accuracy: 96.31%
Epoch 3 - Loss: 0.0993, Accuracy: 0.9702
Test Loss: 0.1162
Test Accuracy: 96.47%
Epoch 4 - Loss: 0.0758, Accuracy: 0.9764
Test Loss: 0.0954
Test Accuracy: 97.03%
Epoch 5 - Loss: 0.0576, Accuracy: 0.9821
Test Loss: 0.0788
Test Accuracy: 97.49%
Epoch 6 - Loss: 0.0468, Accuracy: 0.9855
Test Loss: 0.0779
Test Accuracy: 97.63%
Epoch 7 - Loss: 0.0365, Accuracy: 0.9882
Test Loss: 0.0776
Test Accuracy: 97.62%
Epoch 8 - Loss: 0.0300, Accuracy: 0.9907
Test Loss: 0.0816
Test Accuracy: 97.69%
Epoch 9 - Loss: 0.0265, Accuracy: 0.9915
Test Loss: 0.0874
Test Accuracy: 97.58%
Epoch 10 - Loss: 0.0218, Accuracy: 0.9930
Test Loss: 0.0791
Test Accuracy: 97.70%


In [30]:
import torch 
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

housing = fetch_california_housing()
X_real = housing.data
y_real = housing.target
feature_names = housing.feature_names


print('the shape of X_real is: ',X_real.shape)
print('the shape of y_real is: ',y_real.shape)



x_train, x_val, y_train, y_val = train_test_split(
    X_real, y_real, 
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()
x_train_scaler = scaler.fit_transform(x_train)
x_val_scaler = scaler.transform(x_val)

print('the shape of x_train_scaler is: ',x_train_scaler.shape)
print('the shape of x_val_scaler is: ',x_val_scaler.shape)
print('the shape of x_test_scaler is: ',x_val_scaler.shape)

# Convert to PyTorch tensors
X_train_tensor = torch.FloatTensor(x_train_scaler)
y_train_tensor = torch.FloatTensor(y_train).reshape(-1, 1)

X_val_tensor = torch.FloatTensor(x_val_scaler)
y_val_tensor = torch.FloatTensor(y_val).reshape(-1, 1)

X_test_tensor = torch.FloatTensor(x_val_scaler)
y_test_tensor = torch.FloatTensor(y_val).reshape(-1, 1)

print(f"\nTraining set: {X_train_tensor.shape}")
print(f"Validation set: {X_val_tensor.shape}")
print(f"Test set: {X_test_tensor.shape}")
print(f"Price range: ${y_real.min()*100000:,.0f} - ${y_real.max()*100000:,.0f}")

the shape of X_real is:  (20640, 8)
the shape of y_real is:  (20640,)
the shape of x_train_scaler is:  (16512, 8)
the shape of x_val_scaler is:  (4128, 8)
the shape of x_test_scaler is:  (4128, 8)

Training set: torch.Size([16512, 8])
Validation set: torch.Size([4128, 8])
Test set: torch.Size([4128, 8])
Price range: $14,999 - $500,001


In [ ]:


class CaliforniaHousingModel(nn.Module):
    """" Neural network  for predicting california housing """
    def __init__(self,input_size=X_train_tensor.shape[1]):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_size, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x)
    

In [32]:

epochs = 100
learning_rate = 0.001
model = CaliforniaHousingModel()

mse = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    model.train()
    permutation = torch.randperm(X_train_tensor.size(0))
    epoch_loss = 0.0
    total_samples = 0
    total_absolute_error = 0.0

    for i in range(0, X_train_tensor.size(0), 64):
        
        indices = permutation[i:i+64]
        x_batch = X_train_tensor[indices] # this way batch the data and shuffle it and this work can do it by DataLoader
        y_batch = y_train_tensor[indices]

        output = model(x_batch)
        loss = mse(output, y_batch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        batch_size = y_batch.size(0)
        total_samples += batch_size
        epoch_loss += loss.item() * batch_size
        total_absolute_error += torch.abs(output - y_batch).sum().item()

    average_loss = epoch_loss / total_samples
    mean_absolute_error = total_absolute_error / total_samples

    model.eval()
    with torch.no_grad():
        
        val_output = model(X_val_tensor)
        val_loss = mse(val_output, y_val_tensor).item()
        val_mae = torch.abs(val_output - y_val_tensor).mean().item()
    if epoch % 20 == 0 :
        print(f"Epoch {epoch} | Train Loss: {average_loss:.4f} | Train MAE: {mean_absolute_error:.4f} | Val Loss: {val_loss:.4f} | Val MAE: {val_mae:.4f}")
    
    

Epoch 0 | Train Loss: 1.6320 | Train MAE: 0.8667 | Val Loss: 0.5768 | Val MAE: 0.5397
Epoch 20 | Train Loss: 0.3323 | Train MAE: 0.4021 | Val Loss: 0.3134 | Val MAE: 0.3871
Epoch 40 | Train Loss: 0.3064 | Train MAE: 0.3804 | Val Loss: 0.2920 | Val MAE: 0.3689
Epoch 60 | Train Loss: 0.2879 | Train MAE: 0.3677 | Val Loss: 0.2837 | Val MAE: 0.3607
Epoch 80 | Train Loss: 0.2757 | Train MAE: 0.3598 | Val Loss: 0.2862 | Val MAE: 0.3636


In [38]:
import streamlit as st
import torch
import torch.nn as nn
from PIL import Image
from torchvision import transforms


# -----------------------------
# Model
# -----------------------------
class MNISTModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# -----------------------------
# Load Model
# -----------------------------
model = MNISTModel()
model.load_state_dict(torch.load("mnist_model.pth", map_location="cpu"))
model.eval()

# -----------------------------
# Streamlit UI
# -----------------------------
st.title("MNIST Digit Classifier")

uploaded_file = st.file_uploader(
    "Upload an image",
    type=["png", "jpg", "jpeg"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("L")

    st.image(image, caption="Uploaded Image", width=200)

    transform = transforms.Compose([
        transforms.Resize((28, 28)),
        transforms.ToTensor(),
    ])

    x = transform(image)

    x = x.unsqueeze(0)

    with torch.no_grad():
        output = model(x)
        prediction = output.argmax(dim=1).item()

    st.success(f"Prediction: {prediction}")

ModuleNotFoundError: No module named 'streamlit'